name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.1.1
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  rxdart: ^0.27.7
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
